/**
 * Endpoints para las operaciones de productos en la API.
 */
export const PRODUCT_ENDPOINTS = {
  CREATE: 'products/products/create/',
  CREATE_ACTIVITY_COMPLETE: 'products/products/activity-complete/',
  CREATE_LODGMENT_COMPLETE: 'products/products/lodgment-complete/',
  CREATE_TRANSPORT_COMPLETE: 'products/products/transport-complete/',
  CREATE_TRANSPORTATION_AVAILABILITY: 'products/products/{id}/transportation-availability/',
  GET_TRANSPORTATION_AVAILABILITY: 'products/products/{id}/transportation-availability/',
  UPDATE_TRANSPORTATION_AVAILABILITY: 'products/products/transportation-availability/{id}/',
  DELETE_TRANSPORTATION_AVAILABILITY: 'products/products/transportation-availability/{id}/',
  CREATE_AVAILABILITY: 'products/products/{id}/availability/',
  GET_AVAILABILITY: 'products/products/{id}/availability/',
  UPDATE_AVAILABILITY: 'products/products/availability/{id}/',
  DELETE_AVAILABILITY: 'products/products/availability/{id}/',
  LIST: 'products/products/',
  GET: 'products/products/{id}/',
  UPDATE: 'products/products/{id}/',
  DELETE: 'products/products/{id}/',
  SEARCH_ADVANCED: 'products/products/search/advanced/',
  SEARCH_QUICK: 'products/products/search/quick/',
  STATS_FILTERS: 'products/products/stats/filters/',
  UPDATE_FLIGHT_AVAILABILITY: 'products/products/{id}/flight-availability/',
  GET_FLIGHT_AVAILABILITY: 'products/products/{id}/flight-availability/',
  CREATE_ROOM_AVAILABILITY: 'products/products/room-availability/',
  GET_ROOM_AVAILABILITY: 'products/products/room-availability/{id}/',
  UPDATE_ROOM_AVAILABILITY: 'products/products/room-availability/{id}/',
  DELETE_ROOM_AVAILABILITY: 'products/products/room-availability/{id}/',
  GET_ROOM_AVAILABILITIES: 'products/products/room/{room_id}/availabilities/',
  GET_LODGMENT_ROOMS_AVAILABILITIES: 'products/products/lodgment/{lodgment_id}/rooms/availabilities/',
  GET_ROOM_QUOTE: 'products/products/room/{room_id}/quote/',
  CHECK_PRODUCT: 'products/products/{metadata_id}/check/',
  CHECK_TRANSPORT: 'products/products/{metadata_id}/transport/check/',
  CHECK_FLIGHT: 'products/products/{metadata_id}/flight/check/',
  CHECK_ROOM: 'products/products/room/{room_id}/check/',
  LIST_LOCATIONS: 'products/locations/',
} as const;